# Parameters with 15 files

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from scipy.stats import multivariate_normal
pd.set_option('display.max_columns', None)  


In [21]:
mypath = 'Datasets/Gaze10minData/'
mydtaframes = {}

for index,files in enumerate(os.listdir(mypath)):
    mydtaframes["df_{}".format(index)] = pd.read_excel('{}/{}'.format(mypath, files),
                                                         sheet_name= 'Sheet1')

In [22]:
mydtaframes['df_1'].head()

ParticipantName  RecordingDuration  RecordingTimestamp LocalTimeStamp  \
0   Proband_31_D2            2895701                 440   13:25:24.097   
1   Proband_31_D2            2895701                 456   13:25:24.114   
2   Proband_31_D2            2895701                 473   13:25:24.131   
3   Proband_31_D2            2895701                 490   13:25:24.147   
4   Proband_31_D2            2895701                 506   13:25:24.164   

   EyeTrackerTimestamp  MouseEventIndex  MouseEventX (MCSpx)  \
0         1.458043e+15              NaN                  NaN   
1         1.458043e+15              NaN                  NaN   
2         1.458043e+15              NaN                  NaN   
3         1.458043e+15              NaN                  NaN   
4         1.458043e+15              NaN                  NaN   

   MouseEventY (MCSpx)  KeyPressEventIndex  StudioEventIndex  \
0                  NaN                 NaN               NaN   
1                  NaN                 NaN               NaN   
2                  NaN                 NaN               NaN   
3                  NaN                 NaN               NaN   
4                  NaN                 NaN               NaN   

   StudioEventIndex_B StudioEvent StudioEvent_B  FixationIndex  SaccadeIndex  \
0                 NaN  0_unstated    0_unstated            NaN           2.0   
1                 NaN  0_unstated    0_unstated            NaN           2.0   
2                 NaN  0_unstated    0_unstated            2.0           NaN   
3                 NaN  0_unstated    0_unstated            2.0           NaN   
4                 NaN  0_unstated    0_unstated            2.0           NaN   

  GazeEventType GazeEventType_B  GazeEventDuration  FixationPointX (MCSpx)  \
0       Saccade         Saccade                133                     NaN   
1       Saccade         Saccade                133                     NaN   
2      Fixation        Fixation                200                    45.0   
3      Fixation        Fixation                200                    45.0   
4      Fixation        Fixation                200                    45.0   

   FixationPointY (MCSpx) AbsoluteSaccadicDirection RelativeSaccadicDirection  \
0                     NaN                       NaN                       NaN   
1                     NaN                       NaN                       NaN   
2                   168.0                    339,44                       NaN   
3                   168.0                    339,44                       NaN   
4                   168.0                    339,44                       NaN   

   GazePointIndex  GazePointX (MCSpx)  GazePointY (MCSpx) PupilLeft  \
0            21.0                66.0               220.0      2,74   
1            22.0                20.0               166.0      2,59   
2            23.0                20.0               168.0       NaN   
3            24.0                36.0               171.0      2,58   
4            25.0                66.0               224.0      2,74   

  PupilRight  ValidityLeft  ValidityRight StudioEventTypeDiff  \
0       2,59           0.0            0.0    Agree_0_unstated   
1       2,54           0.0            0.0    Agree_0_unstated   
2       2,62           4.0            0.0    Agree_0_unstated   
3       2,50           0.0            0.0    Agree_0_unstated   
4       2,60           0.0            0.0    Agree_0_unstated   

  GazeEventTypeDiff  
0     Agree_Saccade  
1     Agree_Saccade  
2    Agree_Fixation  
3    Agree_Fixation  
4    Agree_Fixation

In [23]:
studiodf = {}

for index,frames in enumerate(mydtaframes):
    studiodf["{}".format(index)] = mydtaframes[frames]
    #studiodf["{}".format(index)] = mydtaframes[frames].loc[(mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_1_Scanning") | (mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_2_Skimming") | (mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_3_Reading"),['LocalTimeStamp','FixationPointX (MCSpx)','FixationPointY (MCSpx)','StudioEventTypeDiff']]
# studiodf = df1.loc[(df1['StudioEventTypeDiff'] == "Agree_1_Scanning") | (df1['StudioEventTypeDiff'] == "Agree_2_Skimming") | (df1['StudioEventTypeDiff'] == "Agree_3_Reading"),['LocalTimeStamp','FixationPointX (MCSpx)','FixationPointY (MCSpx)','StudioEventTypeDiff']]
# studiodf.head()

In [24]:
len(studiodf)

13

In [25]:
for frames in studiodf:
    studiodf[frames].fillna(method='ffill', inplace= True)

In [26]:

allData = pd.concat([studiodf['0'],studiodf['1'],studiodf['2'],studiodf['3'],studiodf['4'],studiodf['5'],
                    studiodf['6'],studiodf['7'],studiodf['8'],studiodf['9'],studiodf['10'],studiodf['11'],
                    studiodf['12'],], sort = False)
allData['GazePointX (MCSpx)'].fillna(method='bfill', inplace= True)
allData['GazePointY (MCSpx)'].fillna(method='bfill', inplace= True)

In [27]:
allData['GazePointX (MCSpx)'] = allData['GazePointX (MCSpx)'].diff()
allData['GazePointY (MCSpx)'] = allData['GazePointY (MCSpx)'].diff()
allData['GazePointX (MCSpx)'].fillna(method='bfill', inplace= True)
allData['GazePointY (MCSpx)'].fillna(method='bfill', inplace= True)


In [28]:
allData['GazePointX (MCSpx)'].isna().sum().sum()

0

In [29]:
allData['StudioEventTypeDiff'].unique()

array(['Agree_0_unstated', 'Disagree_5_Unknown_0_unstated',
       'Disagree_5_Unknown_3_Reading', 'Disagree_1_Scanning_3_Reading',
       'Disagree_1_Scanning_5_Unknown', 'Agree_5_Unknown',
       'Disagree_5_Unknown_1_Scanning', 'Agree_1_Scanning',
       'Agree_3_Reading', 'Disagree_1_Scanning_2_Skimming',
       'Disagree_5_Unknown_2_Skimming', 'Agree_2_Skimming',
       'Disagree_1_Scanning_4_MediaView',
       'Disagree_2_Skimming_1_Scanning', 'Disagree_2_Skimming_5_Unknown',
       'Disagree_2_Skimming_3_Reading', 'Disagree_5_Unknown_4_MediaView',
       'Agree_4_MediaView', 'Disagree_4_MediaView_1_Scanning',
       'Disagree_0_unstated_3_Reading', 'Disagree_3_Reading_1_Scanning',
       'Disagree_3_Reading_2_Skimming', 'Disagree_2_Skimming_4_MediaView',
       'Disagree_3_Reading_4_MediaView',
       'Disagree_4_MediaView_2_Skimming',
       'Disagree_4_MediaView_5_Unknown', 'Disagree_3_Reading_5_Unknown',
       'Disagree_1_Scanning_0_unstated', 'Disagree_0_unstated_5_Unknown'

In [30]:
import matplotlib.pyplot as plt

In [31]:
from IPython.display import display

In [32]:
readingData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_3_Reading"]
skimmingData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_2_Skimming"]
scanningData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_1_Scanning"]
unknownData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_5_Unknown"]
mediaViewData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_4_MediaView"]

In [33]:
readingData['GazePointY (MCSpx)'].isna().sum().sum()

0

In [34]:
readingData.head()

ParticipantName  RecordingDuration  RecordingTimestamp LocalTimeStamp  \
4691   Proband_30_D1            3520531               77615   14:47:02.446   
4692   Proband_30_D1            3520531               77629   14:47:02.460   
4693   Proband_30_D1            3520531               77645   14:47:02.476   
4694   Proband_30_D1            3520531               77662   14:47:02.493   
4695   Proband_30_D1            3520531               77679   14:47:02.510   

      EyeTrackerTimestamp  MouseEventIndex  MouseEventX (MCSpx)  \
4691         1.457961e+15             14.0                364.0   
4692         1.457961e+15             14.0                364.0   
4693         1.457961e+15             14.0                364.0   
4694         1.457961e+15             14.0                364.0   
4695         1.457961e+15             14.0                364.0   

      MouseEventY (MCSpx)  KeyPressEventIndex  StudioEventIndex  \
4691                 13.0                52.0               8.0   
4692                 13.0                52.0               8.0   
4693                 13.0                52.0               8.0   
4694                 13.0                52.0               8.0   
4695                 13.0                52.0               8.0   

      StudioEventIndex.1 StudioEvent StudioEvent_B  FixationIndex  \
4691                 8.0   3_Reading     3_Reading          206.0   
4692                 8.0   3_Reading     3_Reading          206.0   
4693                 8.0   3_Reading     3_Reading          206.0   
4694                 8.0   3_Reading     3_Reading          206.0   
4695                 8.0   3_Reading     3_Reading          206.0   

      SaccadeIndex GazeEventType GazeEventType_B  GazeEventDuration  \
4691         410.0      Fixation        Fixation                250   
4692         410.0      Fixation        Fixation                250   
4693         410.0      Fixation        Fixation                250   
4694         410.0      Fixation        Fixation                250   
4695         410.0      Fixation        Fixation                250   

      FixationPointX (MCSpx)  FixationPointY (MCSpx)  \
4691                   162.0                   451.0   
4692                   162.0                   451.0   
4693                   162.0                   451.0   
4694                   162.0                   451.0   
4695                   162.0                   451.0   

     AbsoluteSaccadicDirection RelativeSaccadicDirection  GazePointIndex  \
4691                    348,49                    172,21          4640.0   
4692                    348,49                    172,21          4641.0   
4693                    348,49                    172,21          4642.0   
4694                    348,49                    172,21          4643.0   
4695                    348,49                    172,21          4644.0   

      GazePointX (MCSpx)  GazePointY (MCSpx) PupilLeft PupilRight  \
4691                 0.0                 0.0      2,25       2,43   
4692                 2.0                -1.0      2,29       2,43   
4693                -6.0                21.0      2,26       2,41   
4694                11.0               -20.0      2,24       2,39   
4695                 0.0                 6.0      2,28       2,41   

      ValidityLeft  ValidityRight StudioEventTypeDiff GazeEventTypeDiff  \
4691           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4692           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4693           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4694           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4695           0.0            0.0     Agree_3_Reading    Agree_Fixation   

      StudioEventIndex_B  StudioEventIndex_B.1  Unnamed: 11  
4691                 NaN                   NaN          NaN  
4692                 NaN                   NaN          NaN  
4693                 NaN                  

In [35]:
readCovMat = np.cov((readingData['GazePointX (MCSpx)'],readingData['GazePointY (MCSpx)']))
skimmingCovMat = np.cov((skimmingData['GazePointX (MCSpx)'],skimmingData['GazePointY (MCSpx)']))
scanningCovMat = np.cov((scanningData['GazePointX (MCSpx)'],scanningData['GazePointY (MCSpx)']))
unknownCovMat = np.cov((unknownData['GazePointX (MCSpx)'],unknownData['GazePointY (MCSpx)']))
mediaViewCovMat = np.cov((mediaViewData['GazePointX (MCSpx)'],mediaViewData['GazePointY (MCSpx)']))

display(readCovMat)
display(skimmingCovMat)
display(scanningCovMat)
display(unknownCovMat)
display(mediaViewCovMat)

array([[1179.63428727,  171.67930601],
       [ 171.67930601,  836.91103656]])

array([[1805.68290536,  216.39954858],
       [ 216.39954858, 4072.86681401]])

array([[1852.15462508,  330.37926778],
       [ 330.37926778, 1716.64905786]])

array([[1786.47885221,  598.16561454],
       [ 598.16561454, 2461.48454459]])

array([[1922.47066957, -383.06551818],
       [-383.06551818, 1367.8950435 ]])

In [36]:
readingMeanx = readingData['GazePointX (MCSpx)'].mean()
readingMeany = readingData['GazePointY (MCSpx)'].mean()
readingMeanVector = [readingMeanx,readingMeany]

skimmingMeanx = skimmingData['GazePointX (MCSpx)'].mean()
skimmingMeany = skimmingData['GazePointY (MCSpx)'].mean()
skimmingMeanVector = [skimmingMeanx,skimmingMeany]

scanningMeanx = scanningData['GazePointX (MCSpx)'].mean()
scanningMeany = scanningData['GazePointY (MCSpx)'].mean()
scanningMeanVector = [scanningMeanx,scanningMeany]

unknownMeanx = unknownData['GazePointX (MCSpx)'].mean()
unknownMeany = unknownData['GazePointY (MCSpx)'].mean()
unknownMeanVector = [unknownMeanx,unknownMeany]

mediaViewMeanx = mediaViewData['GazePointX (MCSpx)'].mean()
mediaViewMeany = mediaViewData['GazePointY (MCSpx)'].mean()
mediaViewMeanVector = [mediaViewMeanx,mediaViewMeany]

display(readingMeanVector)
display(skimmingMeanVector)
display(scanningMeanVector)
display(unknownMeanVector)
display(mediaViewMeanVector)


[-0.018223117030612773, 0.04327775196599728]

[0.3212, -0.6845777777777777]

[-0.14131410896028737, -0.08072241069646777]

[-0.04316383904262544, 0.06364754324031643]

[-1.0968448729184925, 0.2287467134092901]

In [37]:
readingPassData = readingData[['GazePointX (MCSpx)','GazePointY (MCSpx)']]
skimmingPassData = skimmingData[['GazePointX (MCSpx)','GazePointY (MCSpx)']]
scanningPassData = scanningData[['GazePointX (MCSpx)','GazePointY (MCSpx)']]
unknownPassData = unknownData[['GazePointX (MCSpx)','GazePointY (MCSpx)']]
mediaViewPassData = mediaViewData[['GazePointX (MCSpx)','GazePointY (MCSpx)']]

In [38]:
readPdf = multivariate_normal.pdf(readingPassData, mean=readingMeanVector, cov=readCovMat)
skimmingPdf = multivariate_normal.pdf(skimmingPassData, mean=skimmingMeanVector, cov=skimmingCovMat)
scanningPdf = multivariate_normal.pdf(scanningPassData, mean=scanningMeanVector, cov=scanningCovMat)
unknownPdf = multivariate_normal.pdf(unknownPassData, mean=unknownMeanVector, cov=unknownCovMat)
mediaViewPdf = multivariate_normal.pdf(mediaViewPassData, mean=mediaViewMeanVector, cov=mediaViewCovMat)

# Parameters all files

In [40]:
mypath_all = 'Datasets/Gaze10minData_all/'
mydtaframes_all = {}

for index,files in enumerate(os.listdir(mypath_all)):
    mydtaframes_all["df_{}".format(index)] = pd.read_excel('{}/{}'.format(mypath_all, files),
                                                         sheet_name= 'Sheet1')

In [41]:
mydtaframes_all['df_1'].head()

ParticipantName  RecordingDuration  RecordingTimestamp LocalTimeStamp  \
0   Proband_31_D2            2895701                 440   13:25:24.097   
1   Proband_31_D2            2895701                 456   13:25:24.114   
2   Proband_31_D2            2895701                 473   13:25:24.131   
3   Proband_31_D2            2895701                 490   13:25:24.147   
4   Proband_31_D2            2895701                 506   13:25:24.164   

   EyeTrackerTimestamp  MouseEventIndex  MouseEventX (MCSpx)  \
0         1.458043e+15              NaN                  NaN   
1         1.458043e+15              NaN                  NaN   
2         1.458043e+15              NaN                  NaN   
3         1.458043e+15              NaN                  NaN   
4         1.458043e+15              NaN                  NaN   

   MouseEventY (MCSpx)  KeyPressEventIndex  StudioEventIndex  \
0                  NaN                 NaN               NaN   
1                  NaN                 NaN               NaN   
2                  NaN                 NaN               NaN   
3                  NaN                 NaN               NaN   
4                  NaN                 NaN               NaN   

   StudioEventIndex_B StudioEvent StudioEvent_B  FixationIndex  SaccadeIndex  \
0                 NaN  0_unstated    0_unstated            NaN           2.0   
1                 NaN  0_unstated    0_unstated            NaN           2.0   
2                 NaN  0_unstated    0_unstated            2.0           NaN   
3                 NaN  0_unstated    0_unstated            2.0           NaN   
4                 NaN  0_unstated    0_unstated            2.0           NaN   

  GazeEventType GazeEventType_B  GazeEventDuration  FixationPointX (MCSpx)  \
0       Saccade         Saccade                133                     NaN   
1       Saccade         Saccade                133                     NaN   
2      Fixation        Fixation                200                    45.0   
3      Fixation        Fixation                200                    45.0   
4      Fixation        Fixation                200                    45.0   

   FixationPointY (MCSpx) AbsoluteSaccadicDirection RelativeSaccadicDirection  \
0                     NaN                       NaN                       NaN   
1                     NaN                       NaN                       NaN   
2                   168.0                    339,44                       NaN   
3                   168.0                    339,44                       NaN   
4                   168.0                    339,44                       NaN   

   GazePointIndex  GazePointX (MCSpx)  GazePointY (MCSpx) PupilLeft  \
0            21.0                66.0               220.0      2,74   
1            22.0                20.0               166.0      2,59   
2            23.0                20.0               168.0       NaN   
3            24.0                36.0               171.0      2,58   
4            25.0                66.0               224.0      2,74   

  PupilRight  ValidityLeft  ValidityRight StudioEventTypeDiff  \
0       2,59           0.0            0.0    Agree_0_unstated   
1       2,54           0.0            0.0    Agree_0_unstated   
2       2,62           4.0            0.0    Agree_0_unstated   
3       2,50           0.0            0.0    Agree_0_unstated   
4       2,60           0.0            0.0    Agree_0_unstated   

  GazeEventTypeDiff  
0     Agree_Saccade  
1     Agree_Saccade  
2    Agree_Fixation  
3    Agree_Fixation  
4    Agree_Fixation

In [42]:
studiodf_all = {}

for index,frames in enumerate(mydtaframes_all):
    studiodf_all["{}".format(index)] = mydtaframes_all[frames]
    #studiodf["{}".format(index)] = mydtaframes[frames].loc[(mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_1_Scanning") | (mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_2_Skimming") | (mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_3_Reading"),['LocalTimeStamp','FixationPointX (MCSpx)','FixationPointY (MCSpx)','StudioEventTypeDiff']]
# studiodf = df1.loc[(df1['StudioEventTypeDiff'] == "Agree_1_Scanning") | (df1['StudioEventTypeDiff'] == "Agree_2_Skimming") | (df1['StudioEventTypeDiff'] == "Agree_3_Reading"),['LocalTimeStamp','FixationPointX (MCSpx)','FixationPointY (MCSpx)','StudioEventTypeDiff']]
# studiodf.head()

In [43]:
len(studiodf_all)

20

In [44]:
for frames in studiodf_all:
    studiodf_all[frames].fillna(method='ffill', inplace= True)

In [46]:

allData_all = pd.concat([studiodf_all['0'],studiodf_all['1'],studiodf_all['2'],studiodf_all['3'],studiodf_all['4'],studiodf_all['5'],
                    studiodf_all['6'],studiodf_all['7'],studiodf_all['8'],studiodf_all['9'],studiodf_all['10'],studiodf_all['11'],
                    studiodf_all['12'],studiodf_all['13'],studiodf_all['14'],studiodf_all['15'],studiodf_all['16'],studiodf_all['17'],
                         studiodf_all['18'],studiodf_all['19'],], sort = False)
allData_all['GazePointX (MCSpx)'].fillna(method='bfill', inplace= True)
allData_all['GazePointY (MCSpx)'].fillna(method='bfill', inplace= True)

In [47]:
allData_all['GazePointX (MCSpx)'] = allData_all['GazePointX (MCSpx)'].diff()
allData_all['GazePointY (MCSpx)'] = allData_all['GazePointY (MCSpx)'].diff()
allData_all['GazePointX (MCSpx)'].fillna(method='bfill', inplace= True)
allData_all['GazePointY (MCSpx)'].fillna(method='bfill', inplace= True)


In [48]:
allData_all['GazePointX (MCSpx)'].isna().sum().sum()

0

In [49]:
allData_all['StudioEventTypeDiff'].unique()

array(['Agree_0_unstated', 'Disagree_5_Unknown_0_unstated',
       'Disagree_5_Unknown_3_Reading', 'Disagree_1_Scanning_3_Reading',
       'Disagree_1_Scanning_5_Unknown', 'Agree_5_Unknown',
       'Disagree_5_Unknown_1_Scanning', 'Agree_1_Scanning',
       'Agree_3_Reading', 'Disagree_1_Scanning_2_Skimming',
       'Disagree_5_Unknown_2_Skimming', 'Agree_2_Skimming',
       'Disagree_1_Scanning_4_MediaView',
       'Disagree_2_Skimming_1_Scanning', 'Disagree_2_Skimming_5_Unknown',
       'Disagree_2_Skimming_3_Reading', 'Disagree_5_Unknown_4_MediaView',
       'Agree_4_MediaView', 'Disagree_4_MediaView_1_Scanning',
       'Disagree_0_unstated_3_Reading', 'Disagree_3_Reading_1_Scanning',
       'Disagree_3_Reading_2_Skimming', 'Disagree_2_Skimming_4_MediaView',
       'Disagree_3_Reading_4_MediaView',
       'Disagree_4_MediaView_2_Skimming',
       'Disagree_4_MediaView_5_Unknown', 'Disagree_3_Reading_5_Unknown',
       'Disagree_1_Scanning_0_unstated', 'Disagree_0_unstated_5_Unknown'

In [50]:
import matplotlib.pyplot as plt

In [51]:
from IPython.display import display

In [52]:
readingData_all = allData_all.loc[allData_all['StudioEventTypeDiff'] == "Agree_3_Reading"]
skimmingData_all = allData_all.loc[allData_all['StudioEventTypeDiff'] == "Agree_2_Skimming"]
scanningData_all = allData_all.loc[allData_all['StudioEventTypeDiff'] == "Agree_1_Scanning"]
unknownData_all = allData_all.loc[allData_all['StudioEventTypeDiff'] == "Agree_5_Unknown"]
mediaViewData_all = allData_all.loc[allData_all['StudioEventTypeDiff'] == "Agree_4_MediaView"]

In [53]:
readingData_all['GazePointY (MCSpx)'].isna().sum().sum()

0

In [54]:
readingData_all.head()

ParticipantName  RecordingDuration  RecordingTimestamp LocalTimeStamp  \
4691   Proband_30_D1            3520531               77615   14:47:02.446   
4692   Proband_30_D1            3520531               77629   14:47:02.460   
4693   Proband_30_D1            3520531               77645   14:47:02.476   
4694   Proband_30_D1            3520531               77662   14:47:02.493   
4695   Proband_30_D1            3520531               77679   14:47:02.510   

      EyeTrackerTimestamp  MouseEventIndex  MouseEventX (MCSpx)  \
4691         1.457961e+15             14.0                364.0   
4692         1.457961e+15             14.0                364.0   
4693         1.457961e+15             14.0                364.0   
4694         1.457961e+15             14.0                364.0   
4695         1.457961e+15             14.0                364.0   

      MouseEventY (MCSpx)  KeyPressEventIndex  StudioEventIndex  \
4691                 13.0                52.0               8.0   
4692                 13.0                52.0               8.0   
4693                 13.0                52.0               8.0   
4694                 13.0                52.0               8.0   
4695                 13.0                52.0               8.0   

      StudioEventIndex.1 StudioEvent StudioEvent_B  FixationIndex  \
4691                 8.0   3_Reading     3_Reading          206.0   
4692                 8.0   3_Reading     3_Reading          206.0   
4693                 8.0   3_Reading     3_Reading          206.0   
4694                 8.0   3_Reading     3_Reading          206.0   
4695                 8.0   3_Reading     3_Reading          206.0   

      SaccadeIndex GazeEventType GazeEventType_B  GazeEventDuration  \
4691         410.0      Fixation        Fixation                250   
4692         410.0      Fixation        Fixation                250   
4693         410.0      Fixation        Fixation                250   
4694         410.0      Fixation        Fixation                250   
4695         410.0      Fixation        Fixation                250   

      FixationPointX (MCSpx)  FixationPointY (MCSpx)  \
4691                   162.0                   451.0   
4692                   162.0                   451.0   
4693                   162.0                   451.0   
4694                   162.0                   451.0   
4695                   162.0                   451.0   

     AbsoluteSaccadicDirection RelativeSaccadicDirection  GazePointIndex  \
4691                    348,49                    172,21          4640.0   
4692                    348,49                    172,21          4641.0   
4693                    348,49                    172,21          4642.0   
4694                    348,49                    172,21          4643.0   
4695                    348,49                    172,21          4644.0   

      GazePointX (MCSpx)  GazePointY (MCSpx) PupilLeft PupilRight  \
4691                 0.0                 0.0      2,25       2,43   
4692                 2.0                -1.0      2,29       2,43   
4693                -6.0                21.0      2,26       2,41   
4694                11.0               -20.0      2,24       2,39   
4695                 0.0                 6.0      2,28       2,41   

      ValidityLeft  ValidityRight StudioEventTypeDiff GazeEventTypeDiff  \
4691           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4692           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4693           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4694           0.0            0.0     Agree_3_Reading    Agree_Fixation   
4695           0.0            0.0     Agree_3_Reading    Agree_Fixation   

      StudioEventIndex_B  StudioEventIndex_B.1  Unnamed: 11  
4691                 NaN                   NaN          NaN  
4692                 NaN                   NaN          NaN  
4693                 NaN                  

In [58]:
readCovMat_all = np.cov((readingData_all['GazePointX (MCSpx)'],readingData_all['GazePointY (MCSpx)']))
skimmingCovMat_all = np.cov((skimmingData_all['GazePointX (MCSpx)'],skimmingData_all['GazePointY (MCSpx)']))
scanningCovMat_all = np.cov((scanningData_all['GazePointX (MCSpx)'],scanningData_all['GazePointY (MCSpx)']))
unknownCovMat_all = np.cov((unknownData_all['GazePointX (MCSpx)'],unknownData_all['GazePointY (MCSpx)']))
mediaViewCovMat_all = np.cov((mediaViewData_all['GazePointX (MCSpx)'],mediaViewData_all['GazePointY (MCSpx)']))

display(readCovMat_all)
display(skimmingCovMat_all)
display(scanningCovMat_all)
display(unknownCovMat_all)
display(mediaViewCovMat_all)

array([[1219.36119249,  132.08377548],
       [ 132.08377548,  708.32083509]])

array([[1729.46174858,  213.14434616],
       [ 213.14434616, 3865.69122351]])

array([[1925.199349  ,  255.68209493],
       [ 255.68209493, 1631.86858628]])

array([[2134.70523252,  692.36575501],
       [ 692.36575501, 2710.03012675]])

array([[1588.30018404, -328.80130858],
       [-328.80130858, 1247.88343492]])

In [56]:
readingMeanx_all = readingData_all['GazePointX (MCSpx)'].mean()
readingMeany_all = readingData_all['GazePointY (MCSpx)'].mean()
readingMeanVector_all = [readingMeanx_all,readingMeany_all]

skimmingMeanx_all = skimmingData_all['GazePointX (MCSpx)'].mean()
skimmingMeany_all = skimmingData_all['GazePointY (MCSpx)'].mean()
skimmingMeanVector_all = [skimmingMeanx_all,skimmingMeany_all]

scanningMeanx_all = scanningData_all['GazePointX (MCSpx)'].mean()
scanningMeany_all = scanningData_all['GazePointY (MCSpx)'].mean()
scanningMeanVector_all = [scanningMeanx_all,scanningMeany_all]

unknownMeanx_all = unknownData_all['GazePointX (MCSpx)'].mean()
unknownMeany_all = unknownData_all['GazePointY (MCSpx)'].mean()
unknownMeanVector_all = [unknownMeanx_all,unknownMeany_all]

mediaViewMeanx_all = mediaViewData_all['GazePointX (MCSpx)'].mean()
mediaViewMeany_all = mediaViewData_all['GazePointY (MCSpx)'].mean()
mediaViewMeanVector_all = [mediaViewMeanx_all,mediaViewMeany_all]

display(readingMeanVector_all)
display(skimmingMeanVector_all)
display(scanningMeanVector_all)
display(unknownMeanVector_all)
display(mediaViewMeanVector_all)


[0.04776158969657473, 0.07900986380656777]

[0.31418546774917383, -0.7167802211252091]

[-0.01577395138226883, -0.026021806482364157]

[-0.036332538613040324, 0.09393248332815038]

[-1.0391618000687048, 0.15080728272071453]