In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from scipy.stats import multivariate_normal
pd.set_option('display.max_columns', None)  


In [5]:
mypath = 'Datasets/Gaze10minData/'
mydtaframes = {}

for index,files in enumerate(os.listdir(mypath)):
    mydtaframes["df_{}".format(index)] = pd.read_excel('{}/{}'.format(mypath, files),
                                                         sheet_name= 'Sheet1')

In [6]:
mydtaframes['df_1'].head()

ParticipantName  RecordingDuration  RecordingTimestamp LocalTimeStamp  \
0   Proband_31_D2            2895701                 440   13:25:24.097   
1   Proband_31_D2            2895701                 456   13:25:24.114   
2   Proband_31_D2            2895701                 473   13:25:24.131   
3   Proband_31_D2            2895701                 490   13:25:24.147   
4   Proband_31_D2            2895701                 506   13:25:24.164   

   EyeTrackerTimestamp  MouseEventIndex  MouseEventX (MCSpx)  \
0         1.458043e+15              NaN                  NaN   
1         1.458043e+15              NaN                  NaN   
2         1.458043e+15              NaN                  NaN   
3         1.458043e+15              NaN                  NaN   
4         1.458043e+15              NaN                  NaN   

   MouseEventY (MCSpx)  KeyPressEventIndex  StudioEventIndex  \
0                  NaN                 NaN               NaN   
1                  NaN                 NaN               NaN   
2                  NaN                 NaN               NaN   
3                  NaN                 NaN               NaN   
4                  NaN                 NaN               NaN   

   StudioEventIndex_B StudioEvent StudioEvent_B  FixationIndex  SaccadeIndex  \
0                 NaN  0_unstated    0_unstated            NaN           2.0   
1                 NaN  0_unstated    0_unstated            NaN           2.0   
2                 NaN  0_unstated    0_unstated            2.0           NaN   
3                 NaN  0_unstated    0_unstated            2.0           NaN   
4                 NaN  0_unstated    0_unstated            2.0           NaN   

  GazeEventType GazeEventType_B  GazeEventDuration  FixationPointX (MCSpx)  \
0       Saccade         Saccade                133                     NaN   
1       Saccade         Saccade                133                     NaN   
2      Fixation        Fixation                200                    45.0   
3      Fixation        Fixation                200                    45.0   
4      Fixation        Fixation                200                    45.0   

   FixationPointY (MCSpx) AbsoluteSaccadicDirection RelativeSaccadicDirection  \
0                     NaN                       NaN                       NaN   
1                     NaN                       NaN                       NaN   
2                   168.0                    339,44                       NaN   
3                   168.0                    339,44                       NaN   
4                   168.0                    339,44                       NaN   

   GazePointIndex  GazePointX (MCSpx)  GazePointY (MCSpx) PupilLeft  \
0            21.0                66.0               220.0      2,74   
1            22.0                20.0               166.0      2,59   
2            23.0                20.0               168.0       NaN   
3            24.0                36.0               171.0      2,58   
4            25.0                66.0               224.0      2,74   

  PupilRight  ValidityLeft  ValidityRight StudioEventTypeDiff  \
0       2,59           0.0            0.0    Agree_0_unstated   
1       2,54           0.0            0.0    Agree_0_unstated   
2       2,62           4.0            0.0    Agree_0_unstated   
3       2,50           0.0            0.0    Agree_0_unstated   
4       2,60           0.0            0.0    Agree_0_unstated   

  GazeEventTypeDiff  
0     Agree_Saccade  
1     Agree_Saccade  
2    Agree_Fixation  
3    Agree_Fixation  
4    Agree_Fixation

In [7]:
studiodf = {}

for index,frames in enumerate(mydtaframes):
    studiodf["{}".format(index)] = mydtaframes[frames]
    #studiodf["{}".format(index)] = mydtaframes[frames].loc[(mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_1_Scanning") | (mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_2_Skimming") | (mydtaframes[frames]['StudioEventTypeDiff'] == "Agree_3_Reading"),['LocalTimeStamp','FixationPointX (MCSpx)','FixationPointY (MCSpx)','StudioEventTypeDiff']]
# studiodf = df1.loc[(df1['StudioEventTypeDiff'] == "Agree_1_Scanning") | (df1['StudioEventTypeDiff'] == "Agree_2_Skimming") | (df1['StudioEventTypeDiff'] == "Agree_3_Reading"),['LocalTimeStamp','FixationPointX (MCSpx)','FixationPointY (MCSpx)','StudioEventTypeDiff']]
# studiodf.head()

In [8]:
len(studiodf)

20

In [9]:
for frames in studiodf:
    studiodf[frames].fillna(method='ffill', inplace= True)

In [10]:

allData = pd.concat([studiodf['0'],studiodf['1'],studiodf['2'],studiodf['3'],studiodf['4'],studiodf['5'],
                    studiodf['6'],studiodf['7'],studiodf['8'],studiodf['9'],studiodf['10'],studiodf['11'],
                    studiodf['12'],studiodf['13'],studiodf['14'],studiodf['15'],studiodf['16'],studiodf['17'],
                    studiodf['18'],studiodf['19'],], sort = False)
allData['FixationPointX (MCSpx)'].fillna(method='bfill', inplace= True)
allData['FixationPointY (MCSpx)'].fillna(method='bfill', inplace= True)

In [11]:
allData['FixationPointX (MCSpx)'] = allData['FixationPointX (MCSpx)'].diff()
allData['FixationPointY (MCSpx)'] = allData['FixationPointY (MCSpx)'].diff()
allData['FixationPointX (MCSpx)'].fillna(method='bfill', inplace= True)
allData['FixationPointY (MCSpx)'].fillna(method='bfill', inplace= True)


In [32]:
allData['StudioEventTypeDiff'].unique()

array(['Agree_0_unstated', 'Disagree_5_Unknown_0_unstated',
       'Disagree_5_Unknown_3_Reading', 'Disagree_1_Scanning_3_Reading',
       'Disagree_1_Scanning_5_Unknown', 'Agree_5_Unknown',
       'Disagree_5_Unknown_1_Scanning', 'Agree_1_Scanning',
       'Agree_3_Reading', 'Disagree_1_Scanning_2_Skimming',
       'Disagree_5_Unknown_2_Skimming', 'Agree_2_Skimming',
       'Disagree_1_Scanning_4_MediaView',
       'Disagree_2_Skimming_1_Scanning', 'Disagree_2_Skimming_5_Unknown',
       'Disagree_2_Skimming_3_Reading', 'Disagree_5_Unknown_4_MediaView',
       'Agree_4_MediaView', 'Disagree_4_MediaView_1_Scanning',
       'Disagree_0_unstated_3_Reading', 'Disagree_3_Reading_1_Scanning',
       'Disagree_3_Reading_2_Skimming', 'Disagree_2_Skimming_4_MediaView',
       'Disagree_3_Reading_4_MediaView',
       'Disagree_4_MediaView_2_Skimming',
       'Disagree_4_MediaView_5_Unknown', 'Disagree_3_Reading_5_Unknown',
       'Disagree_1_Scanning_0_unstated', 'Disagree_0_unstated_5_Unknown'

In [12]:
import matplotlib.pyplot as plt

In [43]:
from IPython.display import display

In [33]:
readingData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_1_Scanning"]
skimmingData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_2_Skimming"]
scanningData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_3_Reading"]
unknownData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_5_Unknown"]
mediaViewData = allData.loc[allData['StudioEventTypeDiff'] == "Agree_4_MediaView"]

In [46]:
readCovMat = np.cov((readingData['FixationPointX (MCSpx)'],readingData['FixationPointY (MCSpx)']))
skimmingCovMat = np.cov((skimmingData['FixationPointX (MCSpx)'],skimmingData['FixationPointY (MCSpx)']))
scanningCovMat = np.cov((scanningData['FixationPointX (MCSpx)'],scanningData['FixationPointY (MCSpx)']))
unknownCovMat = np.cov((unknownData['FixationPointX (MCSpx)'],unknownData['FixationPointY (MCSpx)']))
mediaViewCovMat = np.cov((mediaViewData['FixationPointX (MCSpx)'],mediaViewData['FixationPointY (MCSpx)']))

display(readCovMat)
display(skimmingCovMat)
display(scanningCovMat)
display(unknownCovMat)
display(mediaViewCovMat)

array([[2515.59192225,  -19.91356905],
       [ -19.91356905,  436.1699851 ]])

array([[2171.51980977,  -26.02772484],
       [ -26.02772484, 2033.8265622 ]])

array([[1818.29845049,  -29.88062487],
       [ -29.88062487,   86.47609229]])

array([[1127.7907925 ,  149.01897013],
       [ 149.01897013,  599.13653165]])

array([[689.83922956,  54.92173424],
       [ 54.92173424, 613.63371664]])

In [49]:
readingMeanx = readingData['FixationPointX (MCSpx)'].mean()
readingMeany = readingData['FixationPointY (MCSpx)'].mean()
readingMeanVector = [readingMeanx,readingMeany]

skimmingMeanx = skimmingData['FixationPointX (MCSpx)'].mean()
skimmingMeany = skimmingData['FixationPointY (MCSpx)'].mean()
skimmingMeanVector = [skimmingMeanx,skimmingMeany]

scanningMeanx = scanningData['FixationPointX (MCSpx)'].mean()
scanningMeany = scanningData['FixationPointY (MCSpx)'].mean()
scanningMeanVector = [scanningMeanx,scanningMeany]

unknownMeanx = unknownData['FixationPointX (MCSpx)'].mean()
unknownMeany = unknownData['FixationPointY (MCSpx)'].mean()
unknownMeanVector = [unknownMeanx,unknownMeany]

mediaViewMeanx = mediaViewData['FixationPointX (MCSpx)'].mean()
mediaViewMeany = mediaViewData['FixationPointY (MCSpx)'].mean()
mediaViewMeanVector = [mediaViewMeanx,mediaViewMeany]

display(readingMeanVector)
display(skimmingMeanVector)
display(scanningMeanVector)
display(unknownMeanVector)
display(mediaViewMeanVector)


[0.07644184938036225, 0.11914621067683508]

[0.323772999877606, -0.6836522377707968]

[0.12469486264676968, 0.04143240586305546]

[-0.12107822811927715, 0.08579523858885318]

[-0.39917554105118513, 0.06389556853315012]

In [38]:
readingPassData = readingData[['FixationPointX (MCSpx)','FixationPointY (MCSpx)']]
skimmingPassData = skimmingData[['FixationPointX (MCSpx)','FixationPointY (MCSpx)']]
scanningPassData = scanningData[['FixationPointX (MCSpx)','FixationPointY (MCSpx)']]
unknownPassData = unknownData[['FixationPointX (MCSpx)','FixationPointY (MCSpx)']]
mediaViewPassData = mediaViewData[['FixationPointX (MCSpx)','FixationPointY (MCSpx)']]

In [39]:
readPdf = multivariate_normal.pdf(readingPassData, mean=readingMeanVector, cov=readCovMat)
skimmingPdf = multivariate_normal.pdf(skimmingPassData, mean=skimmingMeanVector, cov=skimmingCovMat)
scanningPdf = multivariate_normal.pdf(scanningPassData, mean=scanningMeanVector, cov=scanningCovMat)
unknownPdf = multivariate_normal.pdf(unknownPassData, mean=unknownMeanVector, cov=unknownCovMat)
mediaViewPdf = multivariate_normal.pdf(mediaViewPassData, mean=mediaViewMeanVector, cov=mediaViewCovMat)

In [ ]:
plt.plot(readingPassData,readPdf)

In [ ]:
plt.plot(skimmingPassData,skimmingPdf)

In [ ]:
plt.plot(scanningPassData,scanningPdf)

In [ ]:
from hidden_markov import hmm

In [ ]:
states = ('Scanning','Skimming','Reading')
observations = ('FixationPointX (MCSpx)','FixationPointY (MCSpx)','GazeEventType')
start_probability = np.matrix('0 0 1')
transition_probability = np.matrix('0.2 0.3 0.5; 0.3 0.6 0.1; 0.5 0.2 0.3')
emission_pprobability = np.matrix('0.1 0.4 0.5; 0.6 0.1 0.3; 0.1 0.7 0.2')
test = hmm(states, observations, start_probability, transition_probability, emission_pprobability)

obs = ('FixationPointX (MCSpx)','FixationPointX (MCSpx)','GazeEventType')

In [ ]:
test.viterbi(obs)